# Sử dụng Node.js để build
FROM node:18 AS build
WORKDIR /app
COPY frontend/. .
RUN npm install
RUN npm run build

# Dùng Nginx để serve React app
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
