version: '3.8'

services:
  backend:
    build:
      context: ./SpaServiceBE
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=tcp:spaservice.database.windows.net,1433;Initial Catalog=spaservice;User ID=spaservice;Password=YOUR_PASSWORD;Encrypt=True;
    restart: always

  frontend:
    build:
      context: ./spaservicefe
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080/api
    depends_on:
      - backend
    restart: always
