// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Application
{
    public string ApplicationId { get; set; }

    public string Status { get; set; }

    public string Content { get; set; }

    public string AccountId { get; set; }

    public DateTime CreatedAt { get; set; }

    public string ResolvedBy { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<GuestApplication> GuestApplications { get; set; } = new List<GuestApplication>();

    public virtual Manager ResolvedByNavigation { get; set; }
}