// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Appointment
{
    public string AppointmentId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public string Status { get; set; }

    public string RequestId { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string RoomId { get; set; }

    public string EmployeeId { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Request Request { get; set; }

    public virtual Room Room { get; set; }
}