// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class CategoryEmployee
{
    public string CategoryEmployeeId { get; set; }

    public string CategoryId { get; set; }

    public string EmployeeId { get; set; }

    public virtual ServiceCategory Category { get; set; }

    public virtual Employee Employee { get; set; }
}