// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class CosmeticProduct
{
    public string ProductId { get; set; }

    public string ProductName { get; set; }

    public float Price { get; set; }

    public int Quantity { get; set; }

    public string Description { get; set; }

    public bool Status { get; set; }

    public bool IsSelling { get; set; }

    public string Image { get; set; }

    public string CategoryId { get; set; }

    public virtual CosmeticCategory Category { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}