// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class CosmeticTransaction
{
    public string CosmeticTransactionId { get; set; }

    public string TransactionId { get; set; }

    public string OrderId { get; set; }

    public virtual Order Order { get; set; }

    public virtual Transaction Transaction { get; set; }
}