// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Customer
{
    public string CustomerId { get; set; }

    public string AccountId { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public DateTime DateOfBirth { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<CustomerMembership> CustomerMemberships { get; set; } = new List<CustomerMembership>();

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Request> Requests { get; set; } = new List<Request>();
}