// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class EmployeeCommission
{
    public string EmployeeId { get; set; }

    public string CommissionId { get; set; }

    public string TransactionId { get; set; }

    public float CommissionValue { get; set; }

    public string ServiceTransactionId { get; set; }

    public virtual Commission Commission { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ServiceTransaction ServiceTransaction { get; set; }
}