// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Feedback
{
    public string FeedbackId { get; set; }

    public string FeedbackMessage { get; set; }

    public byte Rating { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string ServiceId { get; set; }

    public virtual Customer CreatedByNavigation { get; set; }

    public virtual SpaService Service { get; set; }
}