// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Floor
{
    public string FloorId { get; set; }

    public int FloorNum { get; set; }

    public string CategoryId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ServiceCategory Category { get; set; }

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}