// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Manager
{
    public string ManagerId { get; set; }

    public string FullName { get; set; }

    public string Position { get; set; }

    public DateOnly HireDate { get; set; }

    public string Status { get; set; }

    public string Image { get; set; }

    public string AccountId { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();
}