// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Membership
{
    public string MembershipId { get; set; }

    public string Type { get; set; }

    public float TotalPayment { get; set; }

    public int Discount { get; set; }

    public virtual ICollection<CustomerMembership> CustomerMemberships { get; set; } = new List<CustomerMembership>();

    public virtual ICollection<ServiceTransaction> ServiceTransactions { get; set; } = new List<ServiceTransaction>();
}