// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class News
{
    public string NewsId { get; set; }

    public string Header { get; set; }

    public string Content { get; set; }

    public string Type { get; set; }

    public string Image { get; set; }

    public string CategoryId { get; set; }

    public virtual ServiceCategory Category { get; set; }
}