// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Promotion
{
    public string PromotionId { get; set; }

    public float DiscountValue { get; set; }

    public string PromotionCode { get; set; }

    public string PromotionName { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}