// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Request
{
    public string RequestId { get; set; }

    public DateTime StartTime { get; set; }

    public string Status { get; set; }

    public string CustomerNote { get; set; }

    public string ManagerNote { get; set; }

    public string ServiceId { get; set; }

    public string CustomerId { get; set; }

    public string EmployeeId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual SpaService Service { get; set; }

    public virtual ICollection<ServiceTransaction> ServiceTransactions { get; set; } = new List<ServiceTransaction>();
}