// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Role
{
    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}