// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Room
{
    public string RoomId { get; set; }

    public int RoomNum { get; set; }

    public string FloorId { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual Floor Floor { get; set; }
}