// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class ServiceTransaction
{
    public string ServiceTransactionId { get; set; }

    public string TransactionId { get; set; }

    public string RequestId { get; set; }

    public string MembershipId { get; set; }

    public virtual ICollection<EmployeeCommission> EmployeeCommissions { get; set; } = new List<EmployeeCommission>();

    public virtual Membership Membership { get; set; }

    public virtual Request Request { get; set; }

    public virtual Transaction Transaction { get; set; }
}