// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class ServiceCategory
{
    public string CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string CategoryDescription { get; set; }

    public virtual ICollection<CategoryEmployee> CategoryEmployees { get; set; } = new List<CategoryEmployee>();

    public virtual ICollection<Floor> Floors { get; set; } = new List<Floor>();

    public virtual ICollection<News> News { get; set; } = new List<News>();

    public virtual ICollection<SpaService> SpaServices { get; set; } = new List<SpaService>();
}