// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class SpaService
{
    public string ServiceId { get; set; }

    public string ServiceName { get; set; }

    public float Price { get; set; }

    public TimeOnly Duration { get; set; }

    public string Description { get; set; }

    public string ServiceImage { get; set; }

    public string CategoryId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ServiceCategory Category { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<Request> Requests { get; set; } = new List<Request>();
}