// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Entities;

public partial class Transaction
{
    public string TransactionId { get; set; }

    public string TransactionType { get; set; }

    public float TotalPrice { get; set; }

    public bool Status { get; set; }

    public DateTime? CompleteTime { get; set; }

    public string PromotionId { get; set; }

    public string PaymentType { get; set; }

    public virtual ICollection<CosmeticTransaction> CosmeticTransactions { get; set; } = new List<CosmeticTransaction>();

    public virtual Promotion Promotion { get; set; }

    public virtual ICollection<ServiceTransaction> ServiceTransactions { get; set; } = new List<ServiceTransaction>();
}