name: Deploy React to Azure

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/react-fe:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/react-fe:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "spaservicefe"  # Thay thế bằng tên app trên Azure
          slot-name: "production"
          images: ${{ secrets.ACR_LOGIN_SERVER }}/react-fe:latest
      - name: Restart Azure Web App
        run: |
          az webapp restart --name spaservicefe --resource-group spaserviceresource
