# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - spaservice

on:
  push:
    branches:
      - development
  workflow_dispatch:

env:
  CONNECTION_STRING: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: SpaServiceBE/

      - name: dotnet publish
        run: dotnet publish SpaServiceBE/SpaServiceBE/SpaServiceBE.csproj -c Release -o output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: output

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8DA52E5AC79E4443AF8BCED4972C4215 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D8E47C446F9F45018F3E32E3D555A189 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D5C729B1244540A080D3A9C6B1D5AACA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'spaservice'
          slot-name: 'Production'
          package: .
          
