name: Build, Test, and Deploy .NET Core application to Azure

on:
  push:
    branches:
      - development

env:
  AZURE_WEBAPP_NAME: spaservice
  AZURE_WEBAPP_PACKAGE_PATH: SpaServiceBE/publish/
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: SpaServiceBE

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}

      - name: Build project
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ env.WORKING_DIRECTORY }}

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ${{ env.WORKING_DIRECTORY }}

      - name: Run unit tests
        run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build --verbosity normal

      - name: Collect Code Coverage (Optional)
        run: dotnet test ${{ env.WORKING_DIRECTORY }} --collect:"XPlat Code Coverage"

      - name: Upload Code Coverage Report (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: ${{ env.WORKING_DIRECTORY }}/TestResults/

  deploy:
    runs-on: windows-latest
    needs: test # Chỉ chạy nếu test thành công
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
            name: webapp
            path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
         app-name: spaservice
         publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
         package: SpaServiceBE/publish/
